platform :ios, '7.0'
pod "AFNetworking", "~> 2.0"
platform :ios
pod 'MJRefresh', '~> 2.0.1'
pod 'MJExtension', '~> 2.3.5'
pod 'Reachability', '~> 3.2'
platform :ios, '6.1'
pod 'SDWebImage', '~>3.7'
pod 'pop', '~> 1.0.6'
pod 'Fingertips'